unstable_features = true
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
max_width = 130
fn_call_width = 60
chain_width = 60
format_macro_bodies = false
# indent_style = "Visual"
imports_layout = "HorizontalVertical"
group_imports = "StdExternalCrate"
imports_granularity = "One"
edition = "2021"